name: Set up Test Env

description: Set up an environment for a test routine

runs:
  using: composite
  steps:
    - run: |
        # Kill the processes that might be left from the previous workflow job.
        # It's relevant only for self-hosted runners if the workflow jobs don't
        # run inside Docker containers.
        ps aux | grep " tarantool " | awk '{system("kill -9 "$2)}' || true
        ps aux | grep "test-run.py " | awk '{system("kill -9 "$2)}' || true

        # To avoid issues with hanging/slowing tests on high memory use, host
        # configuration must avoid swap memory use.
        if [ "$(uname -s)" != "Darwin" ]; then
            swapoff -a && (free -h || swapinfo -h) || echo "Couldn't disable swap"
        fi

        # Define environment variables.
        echo VARDIR=/tmp/t | tee -a $GITHUB_ENV
        echo TEST_RUN_RETRIES=3 | tee -a $GITHUB_ENV
        echo SERVER_START_TIMEOUT=290 | tee -a $GITHUB_ENV
        echo REPLICATION_SYNC_TIMEOUT=300 | tee -a $GITHUB_ENV
        echo TEST_TIMEOUT=310 | tee -a $GITHUB_ENV
        echo NO_OUTPUT_TIMEOUT=320 | tee -a $GITHUB_ENV
        echo PRESERVE_ENVVARS=VARDIR,TEST_RUN_RETRIES,SERVER_START_TIMEOUT,REPLICATION_SYNC_TIMEOUT,TEST_TIMEOUT,NO_OUTPUT_TIMEOUT,GC64 | tee -a $GITHUB_ENV
      shell: bash
